Prevent View not attached crash
Occurred with no known reason in a device.

2021-09-08 01:58:54.276 12201-12201/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gabrielfeo.touchblocker, PID: 12201
    java.lang.RuntimeException: Unable to start service com.gabrielfeo.touchblocker.service.TouchBlockerService@88c1514 with Intent { act=com.gabrielfeo.touchblocker.ACTION_TOGGLE_BLOCK flg=0x10000000 (has extras) }: java.lang.IllegalArgumentException: View=android.widget.TextView{6895367 V.ED..... ......ID 0,0-0,0} not attached to window manager
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4439)
        at android.app.ActivityThread.access$1900(ActivityThread.java:251)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:250)
        at android.app.ActivityThread.main(ActivityThread.java:7806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.IllegalArgumentException: View=android.widget.TextView{6895367 V.ED..... ......ID 0,0-0,0} not attached to window manager
        at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:582)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:486)
        at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:136)
        at com.gabrielfeo.touchblocker.service.TouchBlockerService.onStartCommand(:11)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4421)
        at android.app.ActivityThread.access$1900(ActivityThread.java:251) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:250) 
        at android.app.ActivityThread.main(ActivityThread.java:7806) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 